config/routes.rb
Metamorphosis::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "pictures#index"

  resources :pictures

  resources :comments

  resources :pictures do
    resources :comments
    member do
      get 'download'
    end
  end

  resources :users do
    resources :comments
    resources :pictures
  end

  match ':action' => 'static#:action'

end

app/models/comment.rb
  # Autoren:  Manuel Mitterer, Matthias Prieth
  # Lizenz:   AGPL 3

class Comment < ActiveRecord::Base
  attr_accessible :picture_id, :user_id, :comment

  belongs_to :picture, :polymorphic => true

  validates_presence_of :comment

  default_scope -> { order('created_at DESC') } #newest comments at the top

  #Comments belong to a user
  belongs_to :user

end

app/controllers/comments_controller.rb
  # Autoren:  Manuel Mitterer, Matthias Prieth
  # Lizenz:   AGPL 3

class CommentsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :user_is_creator, only: [:edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def user_is_creator
    @comment = Comment.find(params[:id])
    unless current_user == @comment.user
      redirect_to root_url
    end
  end

  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
#  def create
#    @comment = Comment.new(params[:comment])
#
#    respond_to do |format|
#      if @comment.save
#        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
#        format.json { render json: @comment, status: :created, location: @comment }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @comment.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  def create
    picture_id = params[:comment][:picture_id]
    @picture = Picture.find(picture_id)
    @comment = @picture.comments.build(params[:comment])
    @comment.picture = @picture
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.js
        format.html { redirect_to root_url }
      else
        format.html { render :new }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

end

app/views/comments/_form.html.erb
<% comment ||= Comment.new %>
<%= form_for comment, :remote => true, :locals => { :picture_id => picture_id } do |f| %>
    <% if comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.text_area :comment, :placeholder => "Write a comment...." %>
    </div>

    <%= f.hidden_field :picture_id, :value => picture_id if defined?(picture_id) %>

    <div class="actions">
      <%= f.submit 'Create Comment', :class => "btn btn-danger" %>
    </div>
<% end %>

app/views/comments/create.js.erb
<% picture_id = params[:comment][:picture_id] %>
<% @comments = Comment.where(:picture_id => picture_id) %>
$('#ajaxComments<%= picture_id %> table').remove();
$('#ajaxComments<%= picture_id %>').prepend('<%= j render :template => 'comments/index', :locals => { :commments => @comments } %>');

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<!-- 
  Autoren:  Manuel Mitterer, Matthias Prieth
  Lizenz:   AGPL 3
 -->
<table>

<% @comments.each do |comment| %>

  <tr>
    <td><%= link_to image_tag(comment.user.profil_pic_url(:thumb).to_s), user_path(comment.user) %>
    </td>
    <td><%= text_area_tag 'prev_comments', comment.comment, :disabled => 'disabled' %></td>

    <% if user_signed_in? && current_user == comment.user %>
    <td>
      <%= link_to edit_comment_path(comment) do %>
        <i class="icon-pencil"></i>
      <% end %>
    </td>
    <td>
      <%= link_to comment, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="icon-remove"></i>
      <% end %>
    </td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @comment.comment %>
</p>

<p>
  <b>Picture:</b>
  <%= @comment.picture_id %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>