config/routes.rb
Metamorphosis::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "pictures#index"

  resources :pictures

  resources :comments

  resources :pictures do
    resources :comments
    member do
      get 'download'
    end
  end

  resources :users do
    resources :comments
    resources :pictures
  end

  match ':action' => 'static#:action'

end

app/models/user.rb
  # Autoren:  Manuel Mitterer, Matthias Prieth
  # Lizenz:   AGPL 3

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,  :omniauthable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :provider, :uid, :profil_pic
  attr_accessible :description, :email, :firstname, :lastname, :password, :salt
  attr_accessible :oauth_token, :oauth_expires_at
  has_many :pictures
  has_many :comments, :through => :pictures

  #maybe implemented in the future
  #has_and_belongs_to_many :rewards
  validates_presence_of :username

  #from CarrierWave gem
  mount_uploader :profil_pic, ImageUploader

  default_scope -> { order('total_likes DESC') } #users with most likes at the top

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.new(username:auth.extra.raw_info.name,
         provider:auth.provider,
         uid:auth.uid,
         email:auth.info.email,
         password:Devise.friendly_token[0,20],
         oauth_token:auth.credentials.token,
         oauth_expires_at:Time.at(auth.credentials.expires_at),
         username:auth.info.name
      )
      if auth.info.image.present?
        user.remote_profil_pic_url = auth.info.image
      end
    end
    user.skip_confirmation! #important you have to User.new and than save it, otherwise confirmationmail will be send
    user.save!
    user
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end

  #just for testing
  #def getLink
  #  facebook.get_object("me")
  #end

  def likePicWall(like_id)
    picture=Picture.find(like_id)
    facebook.put_wall_post(
        "likes a picture on Metamorphosis",
        :name => picture.name+' on Metamorphosis',
        :link => 'http://metamorphosis.mediacube.at/pictures/'+like_id+'/',
        :caption => "Hey guys! Iv'e liked a picture on Metamorphosis!",
        :picture => 'http://metamorphosis.mediacube.at'+picture.image.fixedWidth.url
    )
  rescue Koala::Facebook::APIError => e
    logger.info e.to_s
    nil
  end

  def createPicWall(picture)
    facebook.put_wall_post(
        "created a picture on Metamorphosis",
        :name => picture.name+' on Metamorphosis',
        :link => "http://metamorphosis.mediacube.at/pictures/"+picture.id.to_s+"/",
        :caption => "Hey guys! Iv'e created a picture on Metamorphosis!",
        :picture => 'http://metamorphosis.mediacube.at'+picture.image.fixedWidth.url
    )
  rescue Koala::Facebook::APIError => e
    logger.info e.to_s
    nil
  end
  def nice_username
    self.username.split(' ').map {|w| w.capitalize }.join(' ')
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
  # Autoren:  Manuel Mitterer, Matthias Prieth
  # Lizenz:   AGPL 3

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
  # Autoren:  Manuel Mitterer, Matthias Prieth
  # Lizenz:   AGPL 3

class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :correct_user,  :only => [:edit, :update, :destroy]

  def correct_user
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to root_url, :notice => "You are not the owner of this account."
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])

    Picture.find(:all, @user).each do |picture|
      picture.destroy
    end

    @user.remove_profil_pic!
    @user.remove_profil_pic = true
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br />
    <%= f.text_field :salt %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit "Create User", :class => "btn btn-danger" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!-- 
  Autoren:  Manuel Mitterer, Matthias Prieth
  Lizenz:   AGPL 3
 -->
<h1 class="brand">Top Users</h1>

<div class="CSSTable" >
    <table >
      <tr>
        <td>profil-picture</td>
        <td>username</td>
        <td>total picture likes</td>
        <td>email</td>
        <td>profil-description</td>
        <td>show</td>

      </tr>
    <% @users.each do |user| %>
      <tr>
        <td>
            <%= link_to_user_pic(user) %>
        </td>
        <td><%= user.nice_username %></td>
        <td>
          <span class="badge badge-important">
            <%= user.total_likes %>
          </span>
        </td>
        <td><%= user.email %></td>
        <td><%= user.description %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
    </table>
</div>

<br />
<%-# link_to 'New User', new_user_path -%>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if @user.profil_pic? %>
  <%= image_tag(@user.profil_pic_url(:thumb).to_s) %>
<% else %>
  <%= image_tag('default_profil_pic.jpg') %>
<% end %>
<% if user_signed_in? && current_user == @user %>
<%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<% if @user.description %>
<p>
  <b>Description:</b>
  <%= @user.description %>
</p>
<% end %>
<p>
  <b>Total-likes:</b>
  <%if @user.total_likes.nil? %>
    0
  <% else %>
    <%= @user.total_likes %>
  <% end %>
</p>
<p><b>Pictures created:</b></p>
<div id="masonry-container">
    <% @user.pictures.sort_by{|e| e.pic_likes}.reverse_each do |picture| %>
      <%= render :partial => "shared/singlePin", :locals => {:picture => picture} %>
    <% end %>
</div>