config/routes.rb
Metamorphosis::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "pictures#index"

  resources :pictures

  resources :comments

  resources :pictures do
    resources :comments
    member do
      get 'download'
    end
  end

  resources :users do
    resources :comments
    resources :pictures
  end

  match ':action' => 'static#:action'

end

app/views/shared/_loginHeader.html.erb
<!-- 
  Autoren:  Manuel Mitterer, Matthias Prieth
  Lizenz:   AGPL 3
 -->

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">

      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <%= link_to 'Metamorphosis', root_url, :class => 'brand' %>

      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="divider-vertical"></li>
          <li <% if current_page?(root_url) %>class="active"<% end %>>
            <%= link_to root_url, :id => 'homeLink' do %>
              <i class='icon-home'></i> Home
            <% end %>
          </li>
          <li <% if current_page?(users_path) %>class="active"<% end %>>
            <%= link_to users_path, :id => 'userLink' do %>
              <i class='icon-star'></i> Top Users
            <% end %>
          </li>
          <li <% if current_page?(new_picture_path) %>class="active"<% end %>>
            <%= link_to new_picture_path, :id => 'newPicture' do %>
              <i class='icon-picture'></i> Upload Picture
            <% end %>
          </li>
          <li <% if current_page?("/impressum") %>class="active"<% end %>>
            <%= link_to "/impressum" do %>
              <i class='icon-info-sign'></i> Info  
            <% end %>
          </li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
              <li <% if current_page?(edit_user_registration_path) %>class="active"<% end %>>
                <%= link_to edit_user_registration_path do %>
                  <i class='icon-pencil'></i> Edit Profile
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class='icon-off'></i> Logout
                <% end %>
              </li>
              <li class="divider-vertical"></li>
              <li><%= link_to ("Logged in as "+current_user.nice_username), user_path(current_user) %></li>
              <li><%= link_to image_tag(current_user.profil_pic_url(:thumb).to_s), user_path(current_user), :id => 'user-pic-header' %></li>
          <% else %>
              <li>
                <%= link_to new_user_registration_path do %>
                  <i class='icon-plus-sign'></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                    <i class='icon-user'></i> Login
                <% end %>
              </li>
              <li><%= button_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :class => "btn btn-primary" %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/shared/_singlePin.html.erb
<!-- 
  Autoren:  Manuel Mitterer, Matthias Prieth
  Lizenz:   AGPL 3
 -->
<div class="pin">
    <div class="img-polaroid">
        <figure class="polaroid-images">
            <%= link_to image_tag(picture.image_url(:fixedWidth).to_s), picture.image_url, :class => 'title-img', :rel => 'lightbox[gallery1]', :title => picture.name %>
            <div class="hover-buttons">
                <div class="btn inner-hover">
                    <%= link_to("Download", options = {:controller => :pictures, :action => :download, :id => picture.id}, html_options = {:class => "start-challenge btn download-btn btn-mini btn-danger"}) %>
                    <%= link_to "Start Challenge", new_picture_path(:challenge_picture => picture.id), :class => "start-challenge challenge-btn btn btn-mini btn-info" %>
                    <%= link_to "Details", picture_path(:id => picture.id), :class => "start-challenge details-btn btn btn-mini" %>
                </div>
            </div>
            <figcaption class="pic_name">
                <%= picture.name %>
                <div class="likes">
                <span class="badge badge-important number-likes"><%= picture.pic_likes %></span>
                <% if user_signed_in? %>
                <%= link_to "<i class='icon-thumbs-up'></i>".html_safe, root_url(:like_id => picture.id), { :method => :post, :class => "btn btn-mini btn-like"} %>
                <% end %>
            </div>
            </figcaption>
        </figure>
        <!--fb_like-->
        <div class="fb-like" data-href="http://metamorphosis.mediacube.at/pictures/<%= picture.id.to_s %>" data-send="true" data-layout="button_count" data-width="20" data-show-faces="true"></div>
        <hr class="hr-split">
    </div>
    <div class="text">
        <div class="pic_creator">
            <% if picture.parent %>
                <p><%= link_to_user_pic(picture.parent.user) %>
                <%= link_to_user_name(picture.parent.user) %> created this picture.</p>
                <hr class="hr-split">
                <p><%= link_to_user_pic(picture.user) %>
                <%= link_to_user_name(picture.user) %> modified it.</p>
                <hr class="hr-split">
            <% else %>
                <p><%= link_to_user_pic(picture.user) %>
                <%= link_to_user_name(picture.user) %> created this picture.</p>
            <% end %>
        </div>
        <% if picture.description? %>
            <div class="pic_description">
                <p>description: <%= picture.description %></p>
            </div>
        <% end %>
        <hr class="hr-split-visible">
        <!--fb_comment-->
        <!--<div class="fb-comments" href="<%#= request.env['HTTP_HOST']+'/pictures/'+picture.id.to_s %>" data-width="345" data-num-posts="1"></div>-->
        <div id="ajaxComments<%= picture.id %>" class="ajaxComments">
            <% @comments = Comment.where(:picture_id => picture.id) %>
            <%= render :template => 'comments/index', :locals => { :comments => @comments }%>
            <% picture_id = picture.id %>
            <% if user_signed_in? %>
            <%= render :partial => 'comments/form', :locals => { :picture_id => picture_id} %>
            <% end %>
        </div>
    </div>
    <hr class="hr-split">
</div>