config/routes.rb
Metamorphosis::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "pictures#index"

  resources :pictures

  resources :comments

  resources :pictures do
    resources :comments
    member do
      get 'download'
    end
  end

  resources :users do
    resources :comments
    resources :pictures
  end

  match ':action' => 'static#:action'

end

app/models/picture.rb
  # Autoren:  Manuel Mitterer, Matthias Prieth
  # Lizenz:   AGPL 3

class Picture < ActiveRecord::Base
	attr_accessible :description, :gallery, :name, :parent, :rating, :type, :user_id, :image
	has_many :comments
	belongs_to :user
	belongs_to :parent,
	    :class_name => Picture,
	    :foreign_key => :parent

	has_many :children,
	    :class_name => Picture,
	    :foreign_key => :parent

	validates_presence_of :name
	#validates :name, :presence => true
	#from CarrierWave gem
	mount_uploader :image, ImageUploader
end

app/controllers/pictures_controller.rb
  # Autoren:  Manuel Mitterer, Matthias Prieth
  # Lizenz:   AGPL 3

class PicturesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :download]

  require 'mime/types'
  # GET /pictures
  # GET /pictures.json
  def download
    @picture = Picture.find(params[:id])
    file = @picture.image.path
    disposition = 'attachment'
    mime = MIME::Types.type_for(file).first.content_type

    send_file file, :type => mime, :disposition => disposition
  end
  def like
    if session[params[:like_id]].nil? #if is no session
        current_user.likePicWall(params[:like_id])
        session[params[:like_id]] = params[:like_id] #store picture_likes in a session
        @picture = Picture.find_by_id(params[:like_id])
        @user = User.find_by_id(@picture.user_id)
        @picture.pic_likes += 1
        @user.total_likes += 1
        @picture.save!
        @user.save!
    end
  end
  def index
    like if params[:like_id]
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
      format.js
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new()

    respond_to do |format|
      format.html # new.html.erb           s
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])
    @picture.user_id = current_user.id
    
    if params[:challenge_picture]
      @picture.parent = Picture.find(params[:challenge_picture])
    end

    respond_to do |format|
      if @picture.save
        current_user.createPicWall(@picture)
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
        format.js
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.remove_image!
    @picture.remove_image = true
    @picture.destroy


    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

end

app/views/pictures/_form.html.erb
<%= form_for(@picture , :remote => true, :multipart => true, :url => pictures_path(@picture, :challenge_picture => params[:challenge_picture])) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :gallery %><br />
    <%= f.text_field :gallery %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Picture', :class => "btn btn-danger" %>
  </div>
<% end %>

app/views/pictures/create.js.erb
alert("test");
console.log("hello");

app/views/pictures/edit.html.erb
<h1 class="brand">Editing pictures</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<!-- 
  Autoren:  Manuel Mitterer, Matthias Prieth
  Lizenz:   AGPL 3
 -->
<h1 id="title" class="brand" xmlns="http://www.w3.org/1999/html">Metamorphosis</h1>
<div id="masonry-container">
    <% @pictures.sort_by{|e| e.pic_likes}.reverse_each do |picture| %>
      <%= render :partial => "shared/singlePin", :locals => {:picture => picture} %>
    <% end %>
</div>

app/views/pictures/new.html.erb
<h1 class="brand">New Picture</h1>

<% if @challenge_picture %>
    <p>Your challenged picture is:</p>
    <%= image_tag @challenge_picture.image_url(:fixedWidth).to_s %>
    <p>Upload here your modified picture and have fun....</p>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>

<!--<div class="cssThumb">-->
<div class="span4">
  <%= render :partial => "shared/singlePin", :locals => {:picture => @picture} %>
</div>
<div class="span6">
  <p>
    <b>Name:</b>
    <%= @picture.name %>
  </p>
  <% if @picture.description %>
  <p>
    <b>Description:</b>
    <%= @picture.description %>
  </p>
  <% end %>
  <% if @picture.parent %>
  <p>
    <b>Parent:</b>
    <%= link_to @picture.parent.name, picture_path(@picture.parent)  %>
  </p>
  <% end %>
  <% if @picture.gallery?%>
  <p>
    <b>Gallery:</b>
    <%= @picture.gallery %>
  </p>
  <% end %>
  <p>
    <b>Creator:</b>
    <%= link_to @picture.user.nice_username, user_path(@picture.user)  %>
  </p>

  <p>
    <b>Picture-likes:</b>
    <%= @picture.pic_likes %>
  </p>
  <p>
    <% if user_signed_in? && current_user == @picture.user %>
    <%= link_to 'Bild löschen', @picture, method: :delete, data: { confirm: 'Sind Sie sicher?' } %>
    <% end %>
  </p>
  <!--fb_like-->
  <div class="fb-like" data-href="<%= request.url %>" data-send="true" data-layout="button_count" data-width="360" data-show-faces="true"></div>
  <!--fb_comment-->
</br>
</br>
<div class="fb-comments" href="<%= request.url %>" data-width="345" data-num-posts="1"></div>
</div>
<hr class="hr-split-visible">
<p>
  <b>Changed Versions:</b>
    <% @picture.children.sort_by{|e| e.pic_likes}.reverse_each do |picture| %>
    <%= render :partial => "shared/singlePin", :locals => {:picture => picture} %>
    <% end %>
</p>